local ZygorGuidesViewer=ZygorGuidesViewer
if not ZygorGuidesViewer then return end
if UnitFactionGroup("player")~="Horde" then return end
if ZGV:DoMutex("TitlesHMOP") then return end
ZygorGuidesViewer.GuideMenuTier = "TRI"
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Dungeons & Raids\\The Bloodseeker")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Dungeons & Raids\\Darkmaster")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Dungeons & Raids\\Defender of the Wall")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Dungeons & Raids\\Delver of the Vaults")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Dungeons & Raids\\The Dissector")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Dungeons & Raids\\The Fearless")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Dungeons & Raids\\Flameweaver")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Dungeons & Raids\\Hellscream's Downfall")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Dungeons & Raids\\Jade Protector")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Dungeons & Raids\\Liberator of Orgrimmar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Dungeons & Raids\\The Locust")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Dungeons & Raids\\The Lucid")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Dungeons & Raids\\The Manipulator")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Dungeons & Raids\\Mistwalker")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Dungeons & Raids\\Mogu-Slayer")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Dungeons & Raids\\The Poisoned Mind")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Dungeons & Raids\\The Prime")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Dungeons & Raids\\Purified Defender")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Dungeons & Raids\\Scarab Lord")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Dungeons & Raids\\Scarlet Commander")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Dungeons & Raids\\Siegebreaker")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Dungeons & Raids\\Storm's End")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Dungeons & Raids\\The Swarmkeeper")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Dungeons & Raids\\Undaunted")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Dungeons & Raids\\The Wind-Reaver")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\General\\The Proven Assailant")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\General\\The Proven Defender")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\General\\The Proven Healer")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\General\\The Relic Hunter")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\General\\Shado-Master")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\General\\The Stormbreaker")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Player versus Player\\Fire-Watcher")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Player versus Player\\Gorgeous")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Player versus Player\\Grievous Gladiator")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Player versus Player\\Khan")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Player versus Player\\Malevolent Gladiator")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Player versus Player\\Prideful Gladiator")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Player versus Player\\Tyrannical Gladiator")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Pet Battles\\Crazy Cat Lady/Man")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Pet Battles\\Tamer")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Pet Battles\\Trainer")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Pet Battles\\Zookeeper")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Professions\\Cooking\\Master of the Ways")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Quests\\Of the Iron Vanguard")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Quests\\Legend of Pandaria")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Quests\\Stormbreaker")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Reputations\\The Beloved")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Reputations\\Farmer")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Reputations\\The Wakener")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Scenarios\\Of the Black Harvest")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\Scenarios\\Scenaturdist")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\World Events\\Brawler")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Mists of Pandaria Titles\\World Events\\Darkspear Revolutionary")
