local ZygorGuidesViewer=ZygorGuidesViewer
if not ZygorGuidesViewer then return end
if UnitFactionGroup("player")~="Horde" then return end
if ZGV:DoMutex("TitlesHWOD") then return end
ZygorGuidesViewer.GuideMenuTier = "TRI"
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Dungeons & Raids\\Defiler's End")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Dungeons & Raids\\Dockmaster")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Dungeons & Raids\\Empire's Twilight")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Dungeons & Raids\\Grimrail Suplexer")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Dungeons & Raids\\The Indomitable")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Dungeons & Raids\\Ironbane")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Dungeons & Raids\\Lord/Lady of Blackrock")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Dungeons & Raids\\The Mine Master")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Dungeons & Raids\\Savage Hero")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Dungeons & Raids\\Scion of Rukhmar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Dungeons & Raids\\Soul Preserver")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Dungeons & Raids\\Spiritwalker")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Dungeons & Raids\\Violet Guardian")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Garrisons\\Architect")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Garrisons\\Captain")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Garrisons\\Draenei Destroyer")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Garrisons\\Dwarfstalker")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Garrisons\\Gnomebane")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Garrisons\\Lord/Lady of War")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Garrisons\\Lumberjack")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Garrisons\\Manslayer")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Garrisons\\Scourge of the Kaldorei")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Garrisons\\Stable Master")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Garrisons\\Terror of the Tushui")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Garrisons\\Timber Lord")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Garrisons\\Warlord of Draenor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Garrisons\\Worgen Hunter")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\General\\Field Photographer")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\General\\Jenkins")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\General\\Predator")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Player versus Player\\Defender of the Horde")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Player versus Player\\Guardian of the Horde")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Player versus Player\\Primal Gladiator")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Player versus Player\\Soldier of the Horde")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Player versus Player\\Warmongering Gladiator")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Player versus Player\\Wild Gladiator")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Professions\\Artisan")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Quests\\Blood Champion")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Quests\\of the Jungle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Reputations\\Conservationist")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Reputations\\of the Frostwolves")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Reputations\\Masked Chuckler")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Reputations\\Spear of Vol'jin")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\Reputations\\Talon King/Queen")
ZygorGuidesViewer:RegisterGuidePlaceholder("Titles\\Warlords of Draenor Titles\\World Events\\Southshore Slayer")
