local ZygorGuidesViewer=ZygorGuidesViewer
if not ZygorGuidesViewer then return end
if ZGV:DoMutex("ProfessionsCSHADOW") then return end
ZygorGuidesViewer.GuideMenuTier = "TRI"
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Alchemy\\Leveling Guides\\Shadowlands Alchemy 1-175")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Blacksmithing\\Leveling Guides\\Shadowlands Blacksmithing 1-100")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Leveling Guides\\Shadowlands Cooking 1-75")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Aethereal Meat (Bastion)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Aethereal Meat (Revendreth)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Creeping Crawler Meat (Maldraxxus)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Creeping Crawler Meat (Ardenweald)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Phantasmal Haunch (Ardenweald)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Phantasmal Haunch (Maldraxxus)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Raw Seraphic Wing")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Shadowy Shank (Ardenweald)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Shadowy Shank (Maldraxxus)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Tenebrous Ribs (Maldraxxus)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Tenebrous Ribs (Ardenweald)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Iridescent Amberjack")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Lost Sole")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Pocked Bonefish")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Silvergill Pike")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Spinefin Piranha")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Elysian Thade")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Enchanting\\Leveling Guides\\Shadowlands Enchanting 1-115")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Engineering\\Leveling Guides\\Shadowlands Engineering 1-100")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Leveling Guides\\Shadowlands Fishing 1-200")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Iridescent Amberjack")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Lost Sole")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Pocked Bonefish")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Silvergill Pike")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Spinefin Piranha")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Elysian Thade")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Leveling Guides\\Shadowlands Herbalism 1-150")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Death Blossom")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Marrowroot")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Vigil's Torch")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Rising Glory")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Widowbloom")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Nightshade")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\First Flower")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Inscription\\Leveling Guides\\Shadowlands Inscription 1-100")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Jewelcrafting\\Leveling Guides\\Shadowlands Jewelcrafting 1-100")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Leatherworking\\Leveling Guides\\Shadowlands Leatherworking 1-100")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Mining\\Leveling Guides\\Shadowlands Mining 1-150")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Elethium Ore")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Laestrite Ore")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Oxxein Ore")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Phaedrum Ore")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Sinvyr Ore")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Solenium Ore")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Progenium Ore")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Leveling Guides\\Shadowlands Skinning 1-150")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Callous Hide (Bastion)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Callous Hide (Ardenweald)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Callous Hide (Maldraxxus)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Desolate Leather (Bastion)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Desolate Leather (Ardenweald)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Desolate Leather (Maldraxxus)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Heavy Callous Hide (Bastion)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Heavy Callous Hide (Ardenweald)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Heavy Callous Hide (Maldraxxus)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Heavy Desolate Leather (Bastion)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Heavy Desolate Leather (Ardenweald)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Heavy Desolate Leather (Maldraxxus)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Pallid Bone (Bastion)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Pallid Bone (Ardenweald)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Pallid Bone (Maldraxxus)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Tailoring\\Leveling Guides\\Shadowlands Tailoring 1-100")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Tailoring\\Farming Guides\\Lightless Silk (Ardenweald)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Tailoring\\Farming Guides\\Lightless Silk (Revendreth)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Tailoring\\Farming Guides\\Shrouded Cloth (Ardenweald)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Tailoring\\Farming Guides\\Shrouded Cloth (Revendreth)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Bronze Helicid")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Bronzewing Vespoid")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Buzz")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Deathrunner")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Forged Spiteflyer")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Genesis Crawler")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Heartbond Lupine")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Pale Regal Cervid")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Raptora Swooper")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Russet Bufonid")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Sundered Zerethsteed")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Tarachnid Creeper")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Vespoid Flutterer")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Ambystan Darter")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Archetype of Metamorphosis")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Archetype of Renewal")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Archetype of Serenity")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Prototickles")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Terror Jelly")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Archetype of Cunning")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Archetype of Discovery")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Archetype of Predation")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Tunneling Vombata")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Viperid Menace")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Archetype of Multiplicity")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Archetype of Survival")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Archetype of Vigilance")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Fierce Scarabid")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Leaping Leporid")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Shelly")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Archetype of Animation")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Stabilized Geomental")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Archetype of Malice")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Archetype of Motion")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Archetype of Satisfaction")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Multichicken")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Violent Poultrid")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Archetype of Focus")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Omnipotential Core")
ZygorGuidesViewer:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Resonant Echo")
