local ZygorGuidesViewer=ZygorGuidesViewer
if not ZygorGuidesViewer then return end
if UnitFactionGroup("player")~="Horde" then return end
if ZGV:DoMutex("HunterPetHMOP") then return end
ZygorGuidesViewer.GuideMenuTier = "TRI"
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Devilsaurs\\Greater Devilsaurs\\Blue Greater Devilsaur")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Devilsaurs\\Greater Devilsaurs\\Black Greater Devilsaur")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Devilsaurs\\Greater Devilsaurs\\Bronze Greater Devilsaur")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Devilsaurs\\Greater Devilsaurs\\Green Greater Devilsaur")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Devilsaurs\\Greater Devilsaurs\\Light Brown Greater Devilsaur")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Quilen\\Armored Stone Quilens\\Blue Armored Stone Quilen")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Quilen\\Armored Stone Quilens\\Green Armored Stone Quilen")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Quilen\\Armored Stone Quilens\\Purple Armored Stone Quilen")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Quilen\\Armored Stone Quilens\\Red Armored Stone Quilen")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Quilen\\Stone Quilen\\Blue Stone Quilen")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Quilen\\Stone Quilen\\Purple Stone Quilen")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Quilen\\Stone Quilen\\Stone Quilen")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Quilen\\Brown Quilen")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Quilen\\Gray Quilen")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Quilen\\Red Quilen")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Quilen\\White Quilen")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Spirit Beasts\\Spirit Porcupines\\Ghostly Blue Spirit Porcupine")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Spirit Beasts\\Spirit Porcupines\\Ghostly Green Spirit Porcupine")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Spirit Beasts\\Spirit Porcupines\\Ghostly Red Spirit Porcupine")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Water Striders\\Fen Striders\\Black Fen Strider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Water Striders\\Fen Striders\\Blue Fen Strider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Water Striders\\Fen Striders\\Green Fen Strider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Water Striders\\Fen Striders\\White Fen Strider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Water Striders\\Plated Water Striders\\Blue Plated Water Strider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Water Striders\\Plated Water Striders\\Green Plated Water Strider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Water Striders\\Plated Water Striders\\Orange Plated Water Strider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Water Striders\\Plated Water Striders\\Red Plated Water Strider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Water Striders\\Plated Water Striders\\Yellow Plated Water Strider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Water Striders\\Blue-Black Water Strider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Water Striders\\Blue-Green Water Strider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Water Striders\\Dark Yellow Water Strider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Water Striders\\Light Yellow Water Strider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Worms\\Silkworms\\Blue Silkworm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Worms\\Silkworms\\Green Silkworm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Worms\\Silkworms\\Purple Silkworm (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Worms\\Silkworms\\Red Silkworm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Worms\\Silkworms\\Yellow Silkworm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Basilisks\\Crested Basilisks\\Black and Blue Crested Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Basilisks\\Crested Basilisks\\Black and Jade Crested Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Basilisks\\Crested Basilisks\\Black and Orange Crested Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Basilisks\\Crested Basilisks\\Black and Purple Crested Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Basilisks\\Crested Basilisks\\Blue Crested Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Basilisks\\Crested Basilisks\\Blue and Jade Crested Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Basilisks\\Crested Basilisks\\Blue and Orange Crested Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Basilisks\\Crested Basilisks\\Blue and Purple Crested Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Basilisks\\Crested Basilisks\\Burgandy and Blue Crested Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Basilisks\\Crested Basilisks\\Burgandy and Orange Crested Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Basilisks\\Crested Basilisks\\Burgandy and Purple Crested Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Basilisks\\Crested Basilisks\\Green and Blue Crested Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Basilisks\\Crested Basilisks\\Green and Jade Crested Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Basilisks\\Crested Basilisks\\Green and Orange Crested Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Basilisks\\Crested Basilisks\\Green and Purple Crested Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Basilisks\\Crested Basilisks\\Orange-Purple and Blue Crested Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Basilisks\\Crested Basilisks\\Orange-Purple and Jade Crested Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Basilisks\\Crested Basilisks\\Orange-Purple and Orange Crested Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Basilisks\\Crested Basilisks\\Orange-Purple and Purple Crested Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Basilisks\\Crested Basilisks\\Purple and Blue Crested Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Basilisks\\Crested Basilisks\\Red and Blue Crested Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Basilisks\\Crested Basilisks\\Red and Orange Crested Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Basilisks\\Crested Basilisks\\White and Blue Crested Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Basilisks\\Crested Basilisks\\White and Jade Crested Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Basilisks\\Crested Basilisks\\White and Orange Crested Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Basilisks\\Crested Basilisks\\White and Purple Crested Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Basilisks\\Crested Basilisks\\Yellow and Blue Crested Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Basilisks\\Crested Basilisks\\Yellow and Jade Crested Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Basilisks\\Crested Basilisks\\Yellow and Orange Crested Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Basilisks\\Crested Basilisks\\Yellow and Purple Crested Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Basilisks\\Three-Eyed Basilisks\\Green Three-Eyed Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Basilisks\\Three-Eyed Basilisks\\Purple Three-Eyed Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Basilisks\\Three-Eyed Basilisks\\Red Three-Eyed Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Basilisks\\Three-Eyed Basilisks\\Yellow Three-Eyed Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Grand Lion\\Grand Lion (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Grand Tigers\\Black Grand Tiger")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Grand Tigers\\Black-Nosed Orange Grand Tiger")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Grand Tigers\\Brown Grand Tiger")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Grand Tigers\\Grey Grand Tiger")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Grand Tigers\\Orange-Striped Green Grand Tiger")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Grand Tigers\\Pink-Nosed Orange Grand Tiger")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Grand Tigers\\Red Grand Tiger")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Grand Tigers\\White Grand Tiger")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Mystic Cats\\Jade Mystic Cat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cranes\\Black Crane")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cranes\\Blue Crane")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cranes\\Brown Crane")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cranes\\Green Crane")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cranes\\Pink Crane")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cranes\\White Crane")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Direhorns\\Blue Direhorn")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Direhorns\\Brown Direhorn")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Direhorns\\Green Direhorn")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Direhorns\\Pale Direhorn")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Direhorns\\Red Direhorn")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Goats\\Black Goat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Goats\\Black Spotted Goat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Goats\\Brown Goat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Goats\\Brown Spotted Goat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Goats\\Grey Goat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Goats\\White Goat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Porcupines\\Blue Porcupine")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Porcupines\\Brown Porcupine")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Porcupines\\Gray Porcupine")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Porcupines\\Red Porcupine")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Porcupines\\White Porcupine")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Porcupines\\Yellow Porcupine")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Raptors\\Saddled Raptors\\Orange Saddled Raptor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Raptors\\Armored Raptors\\Orange Armored Raptor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Raptors\\Armored Raptors\\Red Armored Raptor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Scorpids\\Crystal Scorpions\\Amber Crystal Scorpion")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Scorpids\\Rugged Scorpions\\Black Rugged Scorpion")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Scorpids\\Rugged Scorpions\\Red Rugged Scorpion")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Wolves\\Saber Worgs\\Ghostly White Saber Worg")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Wolves\\Saber Worgs\\Stormy Dark Grey Saber Worg")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Birds of Prey\\Parrots\\Brown Parrot")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Birds of Prey\\Raven")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Moths\\Blue-Magenta and Yellow Moth")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Moths\\Green and Yellow Moth")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wasps\\Boss Wasps\\Purple Boss Wasp")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Crabs\\Spiked Crabs\\Blue-Marked Blue Spiked Crab")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Crabs\\Spiked Crabs\\Blue-Marked Dark Blue Spiked Crab")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Crabs\\Spiked Crabs\\Blue-Marked Deep Red Spiked Crab")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Crabs\\Spiked Crabs\\Blue-Marked Orange Spiked Crab")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Crabs\\Spiked Crabs\\Blue-Marked Red Spiked Crab")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Crabs\\Spiked Crabs\\Greenish-Blue Spiked Crab")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Crabs\\Spiked Crabs\\Metallic Blue Spiked Crab")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Crabs\\Spiked Crabs\\Purple-Marked Dark Purple Spiked Crab")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Crabs\\Spiked Crabs\\Purple-Marked Green Spiked Crab")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Crabs\\Spiked Crabs\\Purple-Marked Orange Spiked Crab")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Crabs\\Spiked Crabs\\Purple-Marked Red Spiked Crab")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Turtles\\Dragon Turtles\\Black Dragon Turtle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Turtles\\Dragon Turtles\\Blue Dragon Turtle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Turtles\\Dragon Turtles\\Blue Glowing Dragon Turtle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Turtles\\Dragon Turtles\\Brown Dragon Turtle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Turtles\\Dragon Turtles\\Camo Dragon Turtle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Turtles\\Dragon Turtles\\Gold Dragon Turtle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Turtles\\Dragon Turtles\\Green Dragon Turtle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Turtles\\Dragon Turtles\\Red Dragon Turtle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Turtles\\Spiked Dragon Turtles\\Black Spiked Dragon Turtle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Turtles\\Spiked Dragon Turtles\\Blue Spiked Dragon Turtle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Turtles\\Spiked Dragon Turtles\\Brown Spiked Dragon Turtle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Turtles\\Spiked Dragon Turtles\\Gold Spiked Dragon Turtle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Turtles\\Spiked Dragon Turtles\\Green Spiked Dragon Turtle")
