local ZygorGuidesViewer=ZygorGuidesViewer
if not ZygorGuidesViewer then return end
if UnitFactionGroup("player")~="Horde" then return end
if ZGV:DoMutex("PetsMountsHMOP") then return end
ZygorGuidesViewer.GuideMenuTier = "TRI"
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Dropped Mounts\\Amber Primordial Direhorn")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Dropped Mounts\\Black Primal Raptor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Dropped Mounts\\Cobalt Primordial Direhorn")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Dropped Mounts\\Green Primal Raptor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Dropped Mounts\\Jade Primordial Direhorn")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Dropped Mounts\\Red Primal Raptor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Dropped Mounts\\Slate Primordial Direhorn")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Dropped Mounts\\Son of Galleon")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Faction Mounts\\Black Dragon Turtle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Faction Mounts\\Blue Dragon Turtle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Faction Mounts\\Brown Dragon Turtle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Faction Mounts\\Green Dragon Turtle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Faction Mounts\\Purple Dragon Turtle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Faction Mounts\\Red Dragon Turtle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Faction Mounts\\Great Black Dragon Turtle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Faction Mounts\\Great Blue Dragon Turtle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Faction Mounts\\Great Brown Dragon Turtle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Faction Mounts\\Great Green Dragon Turtle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Faction Mounts\\Great Purple Dragon Turtle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Faction Mounts\\Great Red Dragon Turtle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Bone-White Primal Raptor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Miscellaneous\\Crimson Deathcharger")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Ashhide Mushan Beast")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Raid Mounts\\Kor'kron Juggernaut")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Raid Mounts\\Spawn of Horridon")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Reputation Mounts\\Amber Scorpion")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Reputation Mounts\\Azure Riding Crane")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Reputation Mounts\\Azure Water Strider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Reputation Mounts\\Black Riding Goat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Reputation Mounts\\Blue Shado-Pan Riding Tiger")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Reputation Mounts\\Brown Riding Goat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Reputation Mounts\\Crimson Primal Direhorn")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Reputation Mounts\\Golden Primal Direhorn")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Reputation Mounts\\Golden Riding Crane")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Reputation Mounts\\Green Shado-Pan Riding Tiger")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Reputation Mounts\\Red Shado-Pan Riding Tiger")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Reputation Mounts\\Regal Riding Crane")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Reputation Mounts\\White Riding Goat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Unavailable Mounts\\Brawler's Burly Mushan Beast")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Unavailable Mounts\\Kor'kron War Wolf")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Unavailable Mounts\\Primal Flamesaber")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Vendor Mounts\\Blonde Riding Yak")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Vendor Mounts\\Grand Expedition Yak")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Vendor Mounts\\Grey Riding Yak")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Achievement Mounts\\Armored Red Dragonhawk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Achievement Mounts\\Armored Skyscreamer")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Achievement Mounts\\Crimson Cloud Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Achievement Mounts\\Heavenly Crimson Cloud Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Achievement Mounts\\Grand Wyvern")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Achievement Mounts\\Jade Pandaren Kite")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Achievement Mounts\\Pandaren Kite")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Achievement Mounts\\Thundering Jade Cloud Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Achievement Mounts\\Spawn of Galakras")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Blizzard Store Mounts\\Enchanted Fey Dragon")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Blizzard Store Mounts\\Warforged Nightmare")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Blizzard Store Mounts\\Imperial Quilen")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Dropped Mounts\\Thundering Cobalt Cloud Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Dropped Mounts\\Heavenly Onyx Cloud Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Dropped Mounts\\Thundering Onyx Cloud Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Dropped Mounts\\Thundering Ruby Cloud Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Hearthsteed")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Onyx Cloud Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Imperial Quilen")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Profession Mounts\\Engineering\\Depleted-Kyparium Rocket")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Profession Mounts\\Engineering\\Geosynchronous World Spinner")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Profession Mounts\\Engineering\\Sky Golem")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Profession Mounts\\Jewelcrafting\\Jade Panther")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Profession Mounts\\Jewelcrafting\\Jeweled Onyx Panther")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Profession Mounts\\Jewelcrafting\\Ruby Panther")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Profession Mounts\\Jewelcrafting\\Sapphire Panther")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Profession Mounts\\Jewelcrafting\\Sunstone Panther")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Raid Mounts\\Astral Cloud Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Raid Mounts\\Clutch of Ji-kun")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Reputation Mounts\\Azure Cloud Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Reputation Mounts\\Golden Cloud Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Reputation Mounts\\Grand Armored Wyvern")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Reputation Mounts\\Heavenly Golden Cloud Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Reputation Mounts\\Jade Cloud Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Reputation Mounts\\Red Flying Cloud")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Reputation Mounts\\Thundering August Cloud Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Trading Card Mounts\\Ghastly Charger")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Unavailable Mounts\\Armored Bloodwing")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Unavailable Mounts\\Ashen Pandaren Phoenix")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Unavailable Mounts\\Big Blizzard Bear")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Unavailable Mounts\\Crimson Pandaren Phoenix")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Unavailable Mounts\\Emerald Pandaren Phoenix")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Unavailable Mounts\\Grievous Gladiator's Cloud Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Unavailable Mounts\\Malevolent Gladiator's Cloud Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Unavailable Mounts\\Prideful Gladiator's Cloud Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Unavailable Mounts\\Tyrannical Gladiator's Cloud Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Unavailable Mounts\\Violet Pandaren Phoenix")
