local ZygorGuidesViewer=ZygorGuidesViewer
if not ZygorGuidesViewer then return end
if UnitFactionGroup("player")~="Horde" then return end
if ZGV:DoMutex("HunterPetH") then return end
ZygorGuidesViewer.GuideMenuTier = "TRI"
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Chimaeras\\Beige Chimaera")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Chimaeras\\Brown Chimaera")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Chimaeras\\Green Chimaera (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Chimaeras\\Green Plated Chimaera")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Chimaeras\\Purple Plated Chimaera (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Chimaeras\\White Chimaera")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Chimaeras\\White Plated Chimaera (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Chimaeras\\Yellow Plated Chimaera")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Clefthooves\\Rhinos\\Blue Rhino")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Clefthooves\\Rhinos\\Brown Rhino")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Clefthooves\\Rhinos\\Gray Rhino")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Clefthooves\\Rhinos\\White Rhino")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Core Hounds\\Drake Hounds\\Drakeadon (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Core Hounds\\Guardian Hounds\\Gray Guardian Hound")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Devilsaurs\\Black Devilsaur")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Devilsaurs\\Green Devilsaur (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Devilsaurs\\Red Devilsaur")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Devilsaurs\\White Devilsaur")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Shale Spiders\\Green Shale Spider (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Shale Spiders\\Orange Shale Spider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Shale Spiders\\Purple Shale Spider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Shale Spiders\\Red Shale Spider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Silithids\\Ant Silithids\\Brown Ant Silithid")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Silithids\\Ant Silithids\\Green Ant Silithid")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Silithids\\Ant Silithids\\Purple Ant Silithid")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Silithids\\Ant Silithids\\Tan Ant Silithid")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Silithids\\Silithid Colossi\\Blue Silithid Colossi")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Silithids\\Silithid Colossi\\Damaged Blue Silithid Colossi (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Silithids\\Silithid Colossi\\Damaged Orange Silithid Colossi (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Silithids\\Silithid Colossi\\Damaged Pink Silithid Colossi (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Silithids\\Silithid Colossi\\Damaged Purple Silithid Colossi")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Silithids\\Silithid Colossi\\Orange Silithid Colossi (Rare Spawn)")
ZygorGuidesViewer:RegisterGuide("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Silithids\\Silithid Colossi\\Pink Silithid Colossi",{
author="support@zygorguides.com",
description="\nThis guide will walk you through obtaining a Pink Silithid Colossi pet.",
model={37549},
condition_suggested=function() return level>=15 and level<=30 end,
condition_valid=function() return raceclass('Hunter') end,
condition_valid_msg="You must be a hunter to tame pets.",
},[[
step
Switch to the Beast Mastery specialization |complete BeastMastery
|tip You can only tame this pet as a Beast Mastery Hunter.
step
Search for Ainamiss the Hive Queen around the area.
|tip It is level 15-30, depending on your level.
Use your Tame Beast ability on _Ainamiss the Hive Queen_. |cast Tame Beast##1515 |goto Tanaris,34.2,46.0
]])
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Silithids\\Silithid Colossi\\Purple Silithid Colossi")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Silithids\\Green Silithid")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Silithids\\Purple Silithid")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Silithids\\Tan Silithid")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Silithids\\Yellow Silithid")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Spirit Beasts\\Spirit Bears\\Spirit Bear")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Spirit Beasts\\Spirit Birds\\Spectral Owl")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Spirit Beasts\\Spirit Cats\\Blue Spectral Saber Tiger")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Spirit Beasts\\Spirit Cats\\Green Spectral Saber Tiger")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Spirit Beasts\\Spirit Cats\\Spectral Saber Tiger")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Spirit Beasts\\Spirit Cats\\Spirit Leopard")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Spirit Beasts\\Spirit Crabs\\Spectral Spiked Crab")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Spirit Beasts\\Spirit Foxes\\Lightning Spirit Fox (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Spirit Beasts\\Spirit Raptors\\Inky Blue Spirit Raptor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Spirit Beasts\\Spirit Wolves\\Spectral Spirit Wolf")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Spirit Beasts\\Spirit Wolves\\Stormy Dark Blue Spirit Wolf")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Worms\\Jormungars\\Black Jormungar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Worms\\Jormungars\\Blue Jormungar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Worms\\Jormungars\\Ghost Jormungar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Worms\\Jormungars\\Green Jormungar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Worms\\Jormungars\\Purple Jormungar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Worms\\Jormungars\\White Jormungar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Worms\\Blue Worm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Worms\\Brown Worm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Worms\\Ghostly White Worm (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Worms\\Green Worm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Worms\\Gray Worm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Worms\\Pink Worm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Worms\\White Worm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Beast Mastery Exotic Pets\\Worms\\Yellow Worm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Basilisks\\Crested Basilisks\\Burgundy and Jade Crested Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Basilisks\\Crested Basilisks\\Red Basilisk with Jade Fringes")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Beetles\\Scarabs\\Blue-Spotted Teal Scarab")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Beetles\\Scarabs\\Turquoise-Spotted Green Scarab")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Beetles\\Scarabs\\Magenta-Spotted Indigo-Teal Scarab")
ZygorGuidesViewer:RegisterGuide("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Beetles\\Scarabs\\Red-Spotted Green Scarab",{
author="support@zygorguides.com",
description="\nThis guide will walk you through obtaining a Red-Spotted Green Scarab pet.",
model={34912},
condition_suggested=function() return level>=30 and level<=35 end,
condition_valid=function() return raceclass('Hunter') end,
condition_valid_msg="You must be a hunter to tame pets.",
},[[
step
Search for Emerald Scarab around the area.
|tip They are level 30-35, depending on your level.
Use your Tame Beast ability on a _Emerald Scarab_. |cast Tame Beast##1515 |goto Uldum,65.6,32.6
]])
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Beetles\\Scarabs\\Turquoise-Spotted Plum Scarab (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Beetles\\Scarabs\\Yellow-Spotted Brown Scarab")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Beetles\\Blue Beetle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Beetles\\Copper Beetle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Beetles\\Gold Beetle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Beetles\\Gray Beetle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Beetles\\Green Beetle (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Beetles\\Orange Beetle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Beetles\\Purple Beetle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Beetles\\Red Beetle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Beetles\\White Beetle (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Boars\\Felboars\\Black and Green Felboar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Boars\\Felboars\\Blue and White Felboar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Boars\\Felboars\\Gray and Orange Felboar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Boars\\Felboars\\Red and Black Felboar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Boars\\Felboars\\Yellow and Black Felboar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Boars\\Armored Black Boar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Boars\\Armored Brown Boar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Boars\\Armored Ghostly Boar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Boars\\Armored Gray Boar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Boars\\Black Boar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Boars\\Brown Boar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Boars\\Diseased Boar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Boars\\Ghostly Diseased Boar (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Boars\\Gray Boar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Boars\\Red Boar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Boars\\Yellow Boar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Lions\\Black Lion")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Lions\\Gold Lions")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Lions\\Maned Lion (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Lions\\White Lion (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Lynxes\\Brown Lynx")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Lynxes\\Red Lynx")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Mystic Cats\\Black Mystic Cat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Mystic Cats\\Brown and Tan Mystic Cat (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Mystic Cats\\Golden-Tan Mystic Cat (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Mystic Cats\\Obsidian Mystic Cat (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Mystic Cats\\Orange-Striped Green Mystic Cat (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Mystic Cats\\Spotted Black Mystic Cat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Mystic Cats\\Spotted White Mystic Cat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Mystic Cats\\Striped Orange Mystic Cat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Mystic Cats\\Striped White Mystic Cat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Mystic Cats\\White-Striped Black Mystic Cat (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Saber Cats\\Aqua Saber Cat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Saber Cats\\Black Saber Cat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Saber Cats\\Black Striped Saber Cat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Saber Cats\\Icy Blue Saber Cat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Saber Cats\\Lavendar Saber Cat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Saber Cats\\Spotted Orange Saber Cat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Saber Cats\\Spotted White Saber Cat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Saber Cats\\Striped Orange Saber Cat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Saber Cats\\Striped White Saber Cat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Saber Cats\\White Saber Cat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Black Cat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Black-Striped Black Cat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Brown and Tan Cat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Ghostly White Cat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Golden-Tan Cat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Icy Blue Cat (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Orange-Striped Green Cat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Spotted Black Cat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Spotted Orange Cat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Spotted White Cat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Striped Orange Cat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\Striped White Cat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\White Cat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Cats\\White-Striped Black Cat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Dogs\\Demon Dogs\\Blue Demon Dog")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Dogs\\Demon Dogs\\Ghostly Gray Demon Dog")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Dogs\\Demon Dogs\\Ghostly White Demon Dog")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Dogs\\Demon Dogs\\Gray Demon Dog")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Dogs\\Demon Dogs\\Purple Demon Dog")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Dogs\\Demon Dogs\\Red Demon Dog")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Dogs\\Demon Dogs\\White Demon Dog (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Dogs\\Mastiffs\\Black Mastiff")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Dogs\\Mastiffs\\Brown Mastiff")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Dogs\\Mastiffs\\Gray Mastiff")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Dogs\\Mastiffs\\Red Mastiff")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Dogs\\Runed Demon Dogs\\Blue Runed Demon Dog")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Dogs\\Runed Demon Dogs\\Green Runed Demon Dog")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Dogs\\Runed Demon Dogs\\Red Runed Demon Dog")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Foxes\\Black Fox")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Foxes\\Brown Fox")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Foxes\\Gray Fox")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Foxes\\Red Foxes")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Foxes\\White Fox")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Gorillas\\Black Gorilla")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Gorillas\\Dark Gray Gorilla")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Gorillas\\Gray Gorilla")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Gorillas\\Red Gorilla")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Gorillas\\White Gorilla (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Hydras\\Azeroth Hydras\\Orange Azeroth Hydra")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Hyenas\\Brown Hyena")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Hyenas\\Dark Orange Hyena")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Hyenas\\Gray Hyena")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Hyenas\\Orange Hyena")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Hyenas\\Purple Hyena")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Hyenas\\Red Hyena")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Hyenas\\Yellow Hyena")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Monkeys\\Black Monkey")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Monkeys\\Black Monkey with Fez (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Monkeys\\Brown Monkey")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Monkeys\\Dark Gray Monkey")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Monkeys\\Gray Monkey")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Raptors\\Spiky Raptors\\Black Spiky Raptor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Raptors\\Spiky Raptors\\Blue Spiky Raptor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Raptors\\Spiky Raptors\\Brown Spiky Raptor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Raptors\\Spiky Raptors\\Green Spiky Raptor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Raptors\\Spiky Raptors\\Red Spiky Raptor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Raptors\\Black Raptor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Raptors\\Blue Raptor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Raptors\\Green Raptor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Raptors\\Gray Raptor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Raptors\\Orange Raptor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Raptors\\Purple Raptor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Raptors\\Red Raptor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Raptors\\Yellow Raptor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Ravagers\\Dire Ravagers\\Dark Green Dire Ravager")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Ravagers\\Dire Ravagers\\Purple Dire Ravager")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Ravagers\\Dire Ravagers\\Dark Orange and Crimson Dire Ravager")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Ravagers\\Black, Purple, and Rose Ravager")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Ravagers\\Green and Blue Ravager")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Ravagers\\Green and Crimson Ravager")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Ravagers\\Green and Indigo Ravager")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Ravagers\\Green and Yellow Ravager")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Ravagers\\Green, Purple, and Rose Ravager")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Ravagers\\Orange and Black Ravager")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Ravagers\\Orange and Crimson Ravager")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Ravagers\\Orange and Indigo Ravager")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Ravagers\\Orange and Magenta Ravager (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Ravagers\\Purple, Rose, and Blue Ravager #1")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Ravagers\\Purple, Rose, and Blue Ravager #2")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Scorpids\\Fire Scorpions\\Fiery Fire Scorpion")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Scorpids\\Rugged Scorpions\\Blue Rugged Scorpion (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Scorpids\\Rugged Scorpions\\Brown Rugged Scorpion")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Scorpids\\Rugged Scorpions\\Green Rugged Scorpion (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Scorpids\\Black Scorpid")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Scorpids\\Bronze Scorpid")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Scorpids\\Brown Scorpid")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Scorpids\\Green Scorpid")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Scorpids\\Gray Scorpid")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Scorpids\\Pink Scorpid")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Scorpids\\Red Scorpid")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Scorpids\\White Scorpid")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Scorpids\\Yellow Scorpid")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Serpents\\Blue Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Serpents\\Brown Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Serpents\\Crimson Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Serpents\\Green Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Serpents\\Purple Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Serpents\\Ruby Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Serpents\\Teal Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Serpents\\White Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Spiders\\Barbed Spiders\\Orange and Black Barbed Spider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Spiders\\Barbed Spiders\\Red and Black Barbed Spider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Spiders\\Barbed Spiders\\Red and Yellow Barbed Spider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Spiders\\Bone Spiders\\Brown Bone Spider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Spiders\\Bone Spiders\\Dark Brown Bone Spider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Spiders\\Bone Spiders\\Gray Bone Spider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Spiders\\Bone Spiders\\Green-Gray Bone Spider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Spiders\\Bone Spiders\\Rusty Bone Spider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Spiders\\Fire Spiders\\Green Fire Spider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Spiders\\Fire Spiders\\Orange Fire Spider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Spiders\\Fire Spiders\\Purple Fire Spider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Spiders\\Fire Spiders\\Red Fire Spider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Spiders\\Fire Spiders\\Yellow Fire Spider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Spiders\\Tarantulas\\Green Tarantula")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Spiders\\Tarantulas\\Gray Tarantula")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Spiders\\Tarantulas\\Lava Tarantula")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Spiders\\Tarantulas\\Orange Tarantula")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Spiders\\Tarantulas\\Red Tarantula")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Spiders\\Black Widow Spider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Spiders\\Crystal Spider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Spiders\\Green Spider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Spiders\\Gray Spider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Spiders\\Jungle Spider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Spiders\\Olive Spider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Spiders\\Purple Spider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Spiders\\Red Spider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Spiders\\Tan Spider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Tallstriders\\Brown Tallstrider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Tallstriders\\Gray Tallstrider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Tallstriders\\Pink Tallstrider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Tallstriders\\Purple Tallstrider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Tallstriders\\Turqouise Tallstrider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Tallstriders\\White Tallstrider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Warp Stalkers\\Blue Warp Stalker")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Warp Stalkers\\Blue-Green Warp Stalker")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Warp Stalkers\\Green Warp Stalker")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Warp Stalkers\\Red Warp Stalker")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Warp Stalkers\\White Warp Stalker")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Wolves\\Coyotes\\Black Coyote")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Wolves\\Coyotes\\Diseased Coyote")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Wolves\\Coyotes\\Gray Coyote")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Wolves\\Coyotes\\Tan Coyote")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Wolves\\Coyotes\\White Coyote")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Wolves\\Saber Worgs\\Black Saber Worg")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Wolves\\Saber Worgs\\Brown Saber Worg")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Wolves\\Saber Worgs\\Ghostly Black Saber Worg (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Wolves\\Saber Worgs\\Ghostly Brown Saber Worg (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Wolves\\Saber Worgs\\Gray Saber Worg")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Wolves\\Saber Worgs\\White Saber Worg")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Wolves\\Saddled Worgs\\Black Saddled Worg")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Wolves\\Worgs\\Black Worg")
ZygorGuidesViewer:RegisterGuide("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Wolves\\Worgs\\Brown and Gray Worg",{
author="support@zygorguides.com",
description="\nThis guide will walk you through obtaining a Brown and Gray Worg pet.",
model={18063},
condition_suggested=function() return level>=15 and level<=30 end,
condition_valid=function() return raceclass('Hunter') end,
condition_valid_msg="You must be a hunter to tame pets.",
},[[
step
Search for Ironjaw around the area.
|tip They are level 15-30, depending on your level.
Use your Tame Beast ability on _Ironjaw_. |cast Tame Beast##1515 |goto Terokkar Forest,66.6,35.0
]])
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Wolves\\Worgs\\Brown Worg")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Wolves\\Worgs\\Dark Brown Worg (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Wolves\\Worgs\\Dark Gray Worg (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Wolves\\Worgs\\Ghost Worg")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Wolves\\Worgs\\Gray Worg")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Wolves\\Worgs\\Red Worg")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Ground Pets\\Wolves\\Worgs\\Silver Worg")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Bats\\Brown Bat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Bats\\Ghostly Tan Bat (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Bats\\Purple-Red Bat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Bats\\Tan Bat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Bats\\White Bat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Birds of Prey\\Eagles\\Undead Eagle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Birds of Prey\\Hawks\\Black Hawk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Birds of Prey\\Hawks\\Brown Hawk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Birds of Prey\\Owls\\Black Owl")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Birds of Prey\\Owls\\Brown Owl")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Birds of Prey\\Owls\\Dark Brown Owl")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Birds of Prey\\Owls\\Ghostly Green Owl")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Birds of Prey\\Owls\\Gray Owl")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Birds of Prey\\Owls\\Green Owl")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Birds of Prey\\Owls\\Purple Owl")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Birds of Prey\\Owls\\Red and Purple Owl")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Birds of Prey\\Owls\\Red Owl")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Birds of Prey\\Owls\\Sapphire Owl (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Birds of Prey\\Owls\\Spectral Owl")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Birds of Prey\\Owls\\White Owl")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Birds of Prey\\Parrots\\Blue Parrot")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Birds of Prey\\Parrots\\Dark Red Parrot")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Birds of Prey\\Parrots\\Green and Orange Parrot")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Birds of Prey\\Parrots\\Green and Yellow Parrot")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Birds of Prey\\Parrots\\Gray Parrot")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Birds of Prey\\Parrots\\Lavender-Blue Parrot")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Birds of Prey\\Parrots\\Red Parrot")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Birds of Prey\\Parrots\\White Parrot")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Birds of Prey\\Seagull")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Carrion Birds\\Condors\\Blue Condor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Carrion Birds\\Condors\\Gold Condor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Carrion Birds\\Condors\\White Condor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Carrion Birds\\Two-Headed Vultures\\Blue Two-Headed Vulture")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Carrion Birds\\Two-Headed Vultures\\Ghostly Blue Two-Headed Vulture")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Carrion Birds\\Two-Headed Vultures\\Ghostly White Two-Headed Vulture (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Carrion Birds\\Two-Headed Vultures\\Ghostly Yellow Two-Headed Vulture (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Carrion Birds\\Two-Headed Vultures\\Green Two-Headed Vulture")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Carrion Birds\\Two-Headed Vultures\\Red Two-Headed Vulture")
ZygorGuidesViewer:RegisterGuide("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Carrion Birds\\Two-Headed Vultures\\White Two-Headed Vulture",{
author="support@zygorguides.com",
description="\nThis guide will walk you through obtaining a White Two-Headed Vulture pet.",
model={20348},
condition_suggested=function() return level>=15 and level<=30 end,
condition_valid=function() return raceclass('Hunter') end,
condition_valid_msg="You must be a hunter to tame pets.",
},[[
step
Search for Trachela around this area.
|tip They are level 15-30, depending on your level.
Use your Tame Beast ability on _Trachela_. |cast Tame Beast##1515 |goto Terokkar Forest,43.2,51.6
]])
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Carrion Birds\\Two-Headed Vultures\\Yellow Two-Headed Vulture")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Carrion Birds\\Vultures\\Black Vulture")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Carrion Birds\\Vultures\\Blue Vulture")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Carrion Birds\\Vultures\\Brown Vulture")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Carrion Birds\\Vultures\\Ghostly Blue Vulture (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Carrion Birds\\Vultures\\Red Vulture")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Carrion Birds\\Vultures\\White Vulture")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Dragonhawks\\Black Dragonhawk (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Dragonhawks\\Gray Dragonhawk (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Dragonhawks\\Orange Dragonhawk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Dragonhawks\\Orange and Red Dragonhawk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Dragonhawks\\Pink and Purple Dragonhawk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Dragonhawks\\Purple and Cyan Dragonhawk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Dragonhawks\\Red Dragonhawk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Dragonhawks\\Yellow and Pink Dragonhawk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Moths\\Beige Moth")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Moths\\Blue and Magenta Moth")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Moths\\Blue and Yellow Moth")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Moths\\Gray Moth")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Moths\\Green and Blue Moth (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Moths\\Green and Red Moth")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Moths\\Red and Beige Moth")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Moths\\White Moth")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Moths\\White and Yellow Moth (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Nether Rays\\Blue Nether Ray")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Nether Rays\\Gold Nether Ray")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Nether Rays\\Green Nether Ray")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Nether Rays\\Purple Nether Ray")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Nether Rays\\Red Nether Ray")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Serpents\\Arcane Wyrms\\Blue Arcane Wyrm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Serpents\\Arcane Wyrms\\Purple Arcane Wyrm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Serpents\\Arcane Wyrms\\Red Arcane Wyrm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Serpents\\Arcane Wyrms\\White Arcane Wyrm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Sporebats\\Blue Sporebat")
ZygorGuidesViewer:RegisterGuide("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Sporebats\\Brown Sporebat",{
author="support@zygorguides.com",
description="\nThis guide will walk you through obtaining a Brown Sporebat pet.",
model={18029},
condition_suggested=function() return level>=10 and level<=30 end,
condition_valid=function() return raceclass('Hunter') end,
condition_valid_msg="You must be a hunter to tame pets.",
},[[
step
Search for Sporebats around this area.
|tip They are level 10-30, depending on your level.
You can find more around [40.2,53.6].
Use your Tame Beast ability on a _Sporebat_. |cast Tame Beast##1515 |goto Zangarmarsh,64.6,55.2
]])
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Sporebats\\Green Sporebat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wasps\\Boss Wasps\\Blue Boss Wasp")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wasps\\Boss Wasps\\Blue and Red Boss Wasp")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wasps\\Boss Wasps\\Green and Red Boss Wasp")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wasps\\Boss Wasps\\Orange Boss Wasp")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wasps\\Fireflies\\Green Firefly")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wasps\\Fireflies\\Purple with Purple Glow Firefly")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wasps\\Fireflies\\Red Firefly")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wasps\\Fireflies\\Yellow Firefly")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wasps\\Black Wasp (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wasps\\Blue and Red Wasp")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wasps\\Blue Wasp")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wasps\\Copper Wasp (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wasps\\Green and Red Wasp")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wasps\\Green Wasp")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wasps\\Orange Wasp")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wasps\\Purple Wasp")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wasps\\Red Wasp")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wasps\\Tan Wasp")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wasps\\White Wasp (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wasps\\Yellow Wasp")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wind Serpents\\Spiked Wind Serpents\\Blue Spiked Wind Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wind Serpents\\Spiked Wind Serpents\\Blue and White Spiked Wind Serpent (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wind Serpents\\Spiked Wind Serpents\\Gray Spiked Wind Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wind Serpents\\Spiked Wind Serpents\\Gray and Red Spiked Wind Serpent (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wind Serpents\\Spiked Wind Serpents\\Gray and Yellow Spiked Wind Serpent (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wind Serpents\\Spiked Wind Serpents\\Green Spiked Wind Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wind Serpents\\Spiked Wind Serpents\\Red and Gray Spiked Wind Serpent (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wind Serpents\\Spiked Wind Serpents\\Red Spiked Wind Serpent (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wind Serpents\\Spiked Wind Serpents\\White and Gray Spiked Wind Serpent (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wind Serpents\\Spiked Wind Serpents\\White Spiked Wind Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wind Serpents\\Spiked Wind Serpents\\Yellow Spiked Wind Serpent (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wind Serpents\\Dark Blue Wind Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wind Serpents\\Dark Orange Wind Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wind Serpents\\Green Wind Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wind Serpents\\Light Orange Wind Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wind Serpents\\Orange-Winged Red Wind Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wind Serpents\\Red Wind Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Flying Pets\\Wind Serpents\\White Wind Serpent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Crabs\\Spiked Crabs\\Black Spiked Crab")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Crabs\\Spiked Crabs\\Blue Spiked Crab")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Crabs\\Spiked Crabs\\Blue-Marked Black Spiked Crab")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Crabs\\Spiked Crabs\\Gem Crab (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Crabs\\Spiked Crabs\\Green Spiked Crab")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Crabs\\Spiked Crabs\\Green and Blue Spiked Crab")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Crabs\\Spiked Crabs\\Orange Spiked Crab")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Crabs\\Spiked Crabs\\Purple-Marked Black Spiked Crab")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Crabs\\Spiked Crabs\\Purple-Marked Blue Spiked Crab")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Crabs\\Spiked Crabs\\Red Spiked Crab")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Crabs\\Spiked Crabs\\Red-Black Spiked Crab")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Crabs\\Blue Crab")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Crabs\\Bronze Crab")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Crabs\\Red Crab")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Crabs\\White Crab")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Crocolisks\\Greater Crocolisks\\Blue Greater Crocolisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Crocolisks\\Greater Crocolisks\\Brown Greater Crocolisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Crocolisks\\Greater Crocolisks\\Green Greater Crocolisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Crocolisks\\Greater Crocolisks\\Purple Greater Crocolisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Crocolisks\\Greater Crocolisks\\White Greater Crocolisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Crocolisks\\Green Crocolisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Crocolisks\\Gray Crocolisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Crocolisks\\White Crocolisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Crocolisks\\Yellow Crocolisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Turtles\\Ancient Turtles\\Fiery Ancient Turtle (Rare Spawn)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Turtles\\Ancient Turtles\\Green Ancient Turtle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Turtles\\Blue Turtle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Turtles\\Green Turtle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Turtles\\Gray Turtle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Turtles\\Orange Turtle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Hunter Pets\\Water Pets\\Turtles\\White Turtle")
