local ZygorGuidesViewer=ZygorGuidesViewer
if not ZygorGuidesViewer then return end
if UnitFactionGroup("player")~="Alliance" then return end
if ZGV:DoMutex("PetsMountsALEGION") then return end
ZygorGuidesViewer.GuideMenuTier = "TRI"
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Achievement Mounts\\Antoran Gloomhound")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Achievement Mounts\\Defiled Reins")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Achievement Mounts\\Leyfeather Hippogryph")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Achievement Mounts\\Mechanized Lumber Extractor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Achievement Mounts\\Bleakhoof Ruinstrider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Achievement Mounts\\Gilded Ravasaur")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Achievement Mounts\\Seabraid Stallion")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Battle Pet Mounts\\Brilliant Direbeak")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Battle Pet Mounts\\Predatory Bloodgazer")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Battle Pet Mounts\\Snowfeather Hunter")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Battle Pet Mounts\\Viridian Sharptalon")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Blizzard Store Mounts\\Luminous Starseeker")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Blizzard Store Mounts\\Orgrimmar Interceptor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Blizzard Store Mounts\\Shu-zen, the Divine Sentinel")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Blizzard Store Mounts\\Stormwind Skychaser")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Class Mounts\\Death Knight\\Deathlord's Vilebrood Vanquisher")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Class Mounts\\Demon Hunter\\Slayer's Felbroken Shrieker")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Class Mounts\\Hunter\\Huntmaster's Dire Wolfhawk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Class Mounts\\Hunter\\Huntmaster's Fierce Wolfhawk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Class Mounts\\Hunter\\Huntmaster's Loyal Wolfhawk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Class Mounts\\Mage\\Archmage's Prismatic Disc")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Class Mounts\\Monk\\Ban-Lu, Grandmaster's Companion")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Class Mounts\\Paladin\\Highlord's Golden Charger")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Class Mounts\\Paladin\\Highlord's Valorous Charger")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Class Mounts\\Paladin\\Highlord's Vengeful Charger")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Class Mounts\\Paladin\\Highlord's Vigilant Charger")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Class Mounts\\Priest\\High Priest's Lightsworn Seeker")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Class Mounts\\Rogue\\Shadowblade's Baneful Omen")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Class Mounts\\Rogue\\Shadowblade's Crimson Omen")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Class Mounts\\Rogue\\Shadowblade's Lethal Omen")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Class Mounts\\Rogue\\Shadowblade's Murderous Omen")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Class Mounts\\Shaman\\Farseer's Raging Tempest")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Class Mounts\\Warlock\\Netherlord's Accursed Wrathsteed")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Class Mounts\\Warlock\\Netherlord's Brimstone Wrathsteed")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Class Mounts\\Warlock\\Netherlord's Chaotic Wrathsteed")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Class Mounts\\Warrior\\Battlelord's Bloodthirsty War Wyrm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Class Mounts\\Demon Hunter\\Felsaber")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Dropped Mounts\\Abyss Worm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Dropped Mounts\\Acid Belcher")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Dropped Mounts\\Antoran Charhound")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Dropped Mounts\\Darkspore Mana Ray")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Dropped Mounts\\Felglow Mana Ray")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Dropped Mounts\\Fiendish Hellfire Core")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Dropped Mounts\\Lambent Mana Ray")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Dropped Mounts\\Living Infernal Core")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Dropped Mounts\\Scintillating Mana Ray")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Dropped Mounts\\Smoldering Ember Wyrm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Dropped Mounts\\Vibrant Mana Ray")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Dropped Mounts\\Vile Fiend")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Dropped Mounts\\Biletooth Gnasher")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Dropped Mounts\\Crimson Slavermaw")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Dropped Mounts\\Lucid Nightmare")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Dropped Mounts\\Maddened Chaosrunner")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Dropped Mounts\\Midnight's Eternal Reins")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Dropped Mounts\\Shackled Ur'zul")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Long-Forgotten Hippogryph")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Riddler's Mind-Worm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Brawler's Burly Basilisk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Fathom Dweller")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Ratstallion")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Player vs. Player Mounts\\Cruel Gladiator's Storm Dragon")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Player vs. Player Mounts\\Dominant Gladiator's Storm Dragon")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Player vs. Player Mounts\\Fearless Gladiator's Storm Dragon")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Player vs. Player Mounts\\Ferocious Gladiator's Storm Dragon")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Player vs. Player Mounts\\Fierce Gladiator's Storm Dragon")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Player vs. Player Mounts\\Vindictive Gladiator's Storm Dragon")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Ivory Hawkstrider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Prestigious Azure Courser")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Prestigious Bronze Courser")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Prestigious Forest Courser")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Prestigious Ivory Courser")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Prestigious Midnight Courser")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Prestigious Royal Courser")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Prestigious War Steed")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Vicious Gilnean Warhorse")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Vicious War Bear")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Vicious War Elekk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Vicious War Fox")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Vicious War Lion")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Vicious War Turtle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Aquatic Mounts\\Profession Mounts\\Pond Nettle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Profession Mounts\\Brinedeep Bottom-Feeder")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Profession Mounts\\Great Northern Elderhorn")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Profession Mounts\\Spirit of Eche'ro")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Profession Mounts\\Steelbound Devourer")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Quest Mounts\\Violet Spellwing")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Quest Mounts\\Llothien Prowler")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Reputation Mounts\\Arcanist's Manasaber")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Reputation Mounts\\Cloudwing Hippogryph")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Reputation Mounts\\Leywoven Flying Carpet")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Reputation Mounts\\Lightforged Warframe")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Reputation Mounts\\Valarjar Stormwing")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Reputation Mounts\\Amethyst Ruinstrider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Reputation Mounts\\Avenging Felcrusher")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Reputation Mounts\\Beryl Ruinstrider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Reputation Mounts\\Blessed Felcrusher")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Reputation Mounts\\Cerulean Ruinstrider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Reputation Mounts\\Glorious Felcrusher")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Reputation Mounts\\Highmountain Elderhorn")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Reputation Mounts\\Russet Ruinstrider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Reputation Mounts\\Sable Ruinstrider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Reputation Mounts\\Umber Ruinstrider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Reputation Mounts\\Wild Dreamrunner")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Aquatic Mounts\\Vendor Mounts\\Darkwater Skate")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Vendor Mounts\\Yu'lei, Daughter of Jade")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Vendor Mounts\\Arcadian War Turtle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Vendor Mounts\\Bloodfang Widow")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\World Event Mounts\\Darkmoon Dirigible")
