local ZygorGuidesViewer=ZygorGuidesViewer
if not ZygorGuidesViewer then return end
if ZGV:DoMutex("PetsMountsCSHADOW") then return end
ZGV.BETASTART()
ZGV.BETAEND()
ZygorGuidesViewer.GuideMenuTier = "TRI"
ZGV.BETASTART()
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Achievement Mounts\\Rampart Screecher")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Achievement Mounts\\Silky Shimmermoth")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Achievement Mounts\\Sintouched Deathwalker")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Achievement Mounts\\Voracious Gorger")
ZGV.BETAEND()
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Covenant Mounts\\Kyrian Mounts\\Gruesome Flayedwing (Kyrian)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Covenant Mounts\\Kyrian Mounts\\Silvertip Dredwing (Kyrian)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Covenant Mounts\\Kyrian Mounts\\Eternal Phalynx of Courage")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Covenant Mounts\\Kyrian Mounts\\Eternal Phalynx of Humility")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Covenant Mounts\\Kyrian Mounts\\Eternal Phalynx of Loyalty")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Covenant Mounts\\Kyrian Mounts\\Eternal Phalynx of Purity")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Covenant Mounts\\Kyrian Mounts\\Pale Acidmaw (Kyrian)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Covenant Mounts\\Kyrian Mounts\\Phalynx of Courage")
ZGV.BETAEND()
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Covenant Mounts\\Kyrian Mounts\\Phalynx of Purity")
ZGV.BETAEND()
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Covenant Mounts\\Necrolord Mounts\\Dauntless Duskrunner (Necrolord)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Covenant Mounts\\Necrolord Mounts\\Gruesome Flayedwing (Necrolord)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Covenant Mounts\\Necrolord Mounts\\Predatory Plagueroc")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Covenant Mounts\\Necrolord Mounts\\Silvertip Dredwing (Necrolord)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Covenant Mounts\\Necrolord Mounts\\Armored Bonehoof Tauralus")
ZGV.BETAEND()
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Covenant Mounts\\Necrolord Mounts\\Armored Plaguerot Tauralus")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Covenant Mounts\\Necrolord Mounts\\Armored War-Bred Tauralus")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Covenant Mounts\\Necrolord Mounts\\Bonehoof Tauralus")
ZGV.BETAEND()
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Covenant Mounts\\Necrolord Mounts\\Pale Acidmaw (Necrolord)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Covenant Mounts\\Necrolord Mounts\\Plaguerot Tauralus")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Covenant Mounts\\Necrolord Mounts\\War-Bred Tauralus")
ZGV.BETAEND()
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Covenant Mounts\\Night Fae Mounts\\Vibrant Flutterwing")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Covenant Mounts\\Night Fae Mounts\\Dreamlight Runestag")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Covenant Mounts\\Night Fae Mounts\\Enchanted Dreamlight Runestag")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Covenant Mounts\\Night Fae Mounts\\Enchanted Shadeleaf Runestag")
ZGV.BETAEND()
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Covenant Mounts\\Night Fae Mounts\\Enchanted Winterborn Runestag")
ZGV.BETAEND()
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Covenant Mounts\\Night Fae Mounts\\Shadeleaf Runestag")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Covenant Mounts\\Night Fae Mounts\\Umbral Scythehorn")
ZGV.BETAEND()
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Covenant Mounts\\Night Fae Mounts\\Wild Glimmerfur Prowler")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Covenant Mounts\\Night Fae Mounts\\Winterborn Runestag")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Covenant Mounts\\Venthyr Mounts\\Dauntless Duskrunner (Venthyr)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Covenant Mounts\\Venthyr Mounts\\Gruesome Flayedwing (Venthyr)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Covenant Mounts\\Venthyr Mounts\\Horrid Dredwing")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Covenant Mounts\\Venthyr Mounts\\Silvertip Dredwing (Venthyr)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Covenant Mounts\\Venthyr Mounts\\Battle Gargon Silessa")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Covenant Mounts\\Venthyr Mounts\\Battle Gargon Vrednic")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Covenant Mounts\\Venthyr Mounts\\Crypt Gargon")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Covenant Mounts\\Venthyr Mounts\\Desire's Battle Gargon")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Covenant Mounts\\Venthyr Mounts\\Gravestone Battle Armor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Covenant Mounts\\Venthyr Mounts\\Hopecrusher Gargon")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Covenant Mounts\\Venthyr Mounts\\Pale Acidmaw (Venthyr)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Covenant Mounts\\Venthyr Mounts\\Sinfall Gargon")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Dropped Mounts\\Callow Flayedwing")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Dropped Mounts\\Endmire Flyer")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Dropped Mounts\\Hulking Deathroc")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Dropped Mounts\\Marrowfang")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Dropped Mounts\\Shimmermist Runner")
ZGV.BETAEND()
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Dropped Mounts\\Swift Gloomhoof")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Dropped Mounts\\Arboreal Gulper")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Dropped Mounts\\Battle-Bound Warhound")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Dropped Mounts\\Blisterback Bloodtusk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Dropped Mounts\\Gorespine")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Dropped Mounts\\Loyal Gorger")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Dropped Mounts\\Mawsworn Soulhunter")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Dropped Mounts\\Spinemaw Gladechewer")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Ascended Skymane")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Bulbous Necroray")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Chittering Animite")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Highwind Darkmane")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Infested Necroray")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Pestilent Necroray")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Silverwind Larion")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Sundancer")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Wildseed Cradle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Bound Shadehound")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Corridor Creeper")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Darkwarren Hardshell")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Sinrunner Blanchy")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Warstitched Darkhound")
ZGV.BETAEND()
ZGV.BETASTART()
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Reputation Mounts\\The Wild Hunt Mounts\\Amber Ardenmoth")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Reputation Mounts\\The Undying Army\\Colossal Slaughterclaw")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Reputation Mounts\\The Wild Hunt Mounts\\Duskflutter Ardenmoth")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Reputation Mounts\\The Ascended Mounts\\Gilded Prowler")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Reputation Mounts\\Court of Harvestors Mounts\\Court Sinrunner")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Reputation Mounts\\The Avowed Mounts\\Inquisition Gargon")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Reputation Mounts\\The Undying Army\\Lurid Bloodtusk")
ZGV.BETAEND()
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Amber Shardhide")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Ardenweald Wilderling")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Ascendant's Aquilon")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Autumnal Wilderling")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Beryl Shardhide")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Cartel Master's Gearglider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Crimson Shardhide")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Darkmaul")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Dusklight Razorwing")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Elysian Aquilon")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Fallen Charger")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Fierce Razorwing")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Foresworn Aquilon")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Garnet Razorwing")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Hand of Bahmehthra")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Lord of the Corpseflies")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Maldraxxian Corpsefly")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Obsidian Gravewing")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Regal Corpsefly")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Sanctum Gloomcharger")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Sinfall Gravewing")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Soaring Razorwing")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Soulbound Gloomcharger")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Summer Wilderling")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Tamed Mauler")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Undying Darkhound")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Vengeance")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Vicious War Gorm (Alliance)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Vicious War Gorm (Horde)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Wandering Arden Doe")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Wild Hunt Legsplitter")
ZGV.BETAEND()
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Patient Bufonid")
ZGV.BETASTART()
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Bronze Helicid")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Aquatic Mounts\\Miscellaneous Mounts\\Deepstar Aurelid")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Bronzewing Vespoid")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Buzz")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Forged Spiteflyer")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Adorned Vombata")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Deathrunner")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Genesis Crawler")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Pale Regal Cervid")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Raptora Swooper")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Russet Bufonid")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Sundered Zerethsteed")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Tarachnid Creeper")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guide\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Vespoid Flutterer")
ZGV.BETAEND()
