local ZygorGuidesViewer=ZygorGuidesViewer
if not ZygorGuidesViewer then return end
if UnitFactionGroup("player")~="Horde" then return end
if ZGV:DoMutex("AchievementsHLEGION") then return end
ZygorGuidesViewer.GuideMenuTier = "TRI"
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\A Classy Outfit")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\A Glorious Campaign")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\Arsenal of Power")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\Broken Isles Pathfinder, Part One")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\The Original")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\No Mercy")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\With a Vengeance")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Tough Threads")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Lethal Looks")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\The Fierce and the Furious")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Relentlessly Good Looking")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Wrath of the Stich King")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Viciously Vintage")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Ruth(less) is More")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Cataclysmic Catwalk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Why Male(volent) Models?")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Dressed to Oppress")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\It's Not Fashion Unless it Hurts")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Wear it With Pride")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Untamed Beauty")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Wild Style")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\War-Mog-ering")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\More Like Win-dictive")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Cruel Intentions")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Accessor-Eyes")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Azeroth's Next Top Model")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Black is the New Black")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Can I Get A Helya")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Dress in Lairs")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Extreme Makeover: Fel Edition")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Fashionista: Back")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Fashionista: Chest")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Fashionista: Feet")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Fashionista: Hand")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Fashionista: Head")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Fashionista: Legs")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Fashionista: Shirt")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Fashionista: Shoulder")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Fashionista: Tabard")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Fashionista: Waist")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Fashionista: Weapon & Off Hand")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Fashionista: Wrist")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Glamour of Twilight")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Hot Couture")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Make it W-orc W-orc")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Merely a Set")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Mogg-Saron")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Outlandish Style")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Retro Trend")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Sha of Fabulous")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Style of the Crusader")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\So Hot Right Now")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Suns Out, Thori'dals Out")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\That's So Last Mellenium")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Thunderwear")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Undying Aesthetic")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Wardrobe of the Old Gods")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Winter Catalog")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Yaass'shaarj")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Legion\\The Tangerine Traveler")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\A Specter, Illuminated")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Adds? More Like Bads")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Arcanic Cling")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Black Rook Moan")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Burning Down the House")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\But you Say He's Just a Friend")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Can't Eat Just One")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Clean House")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Dropping Some Eaves")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Egg-cellent!")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Got to Ketchum All")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Helheim Hath No Fury")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\I Ain't Even Cold")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\I Got What You Mead")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\I Made a Food!")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Instant Karma")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\No Time to Waste")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Poor Unfortunate Souls")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Ready for Raiding V")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Stag Party")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Stay Salty")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Surge Protector")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Waiting for Gerdo")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Who's Afraid of the Dark")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\You Used to Scrawl Me In Your Fel Tome")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\You're Just Making It WORSE!")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\A Change In Scenery")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Bingo!")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Buggy Fight")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Burning Bridges")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Cage Rematch")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\The Chosen")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Dark Souls")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Elementalry!")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Fel Turkey!")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Five Course Seafood Buffet")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Fruit of All Evil")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Gluten Free")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Grand Fin-ale")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Grand Opening")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Great Soul, Great Purpose")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Grin and Bear it!")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\I Attack the Darkness")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\I've Got My Eyes On You")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Imagined Dragons World Tour")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Infinitesimal")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Gul'dan")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Xavius")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Don't Sweat the Technique")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Hard to Kill")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Hounds Good To Me")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Argus the Unmaker")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Portal Combat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Remember the Titans")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Seat of the Pantheon")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Spheres of Influence")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Stardust Crusaders")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\This is the War Room!")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Together We Stand")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\The World Revolves Around Me")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Worm-monger")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Glory of the Argus Raider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Not For You")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Scare Bear")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Sky Walker")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Took the Red Eye Down")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Unleashed Monstrosities")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Use the Force(s)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Wax on, Wax off")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Webbing Crashers")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Glory of the Legion Hero")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\...And Chew Mana Buns")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Adventurer of Argus")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Broken Isles Explorer")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Broken Isles Pathfinder, Part Two")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Commander of Argus")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Envision Invasion Eradication")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Explore Argus")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Explore Azsuna")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Explore Broken Shore")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Explore Highmountain")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Explore Stormheim")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Explore Suramar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Explore Val'sharah")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Higher Dimensional Learning")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Invasion Obliteration")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\To Kill Demons...")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Paragon of Argus")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Shoot First, Loot Later")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Universal Explorer")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Underbelly Tycoon")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\We Came Here For Two Reasons")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\And We're All Out of Mana Buns")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Feats of Strength\\Promotions\\Collector's Edition: Gilded Ravasaur")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Feats of Strength\\Promotions\\Collector's Edition: Tottle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Aquatic Acquiescence")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Aquatic Assault")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Aquatic Brawler")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Beast Blitz")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Beast Brawler")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Best of the Beasts")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Critical Critters")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Critter Brawler")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Draconic Destruction")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Dragonkin Brawler")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Dragons!")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Elemental Brawler")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Elemental Escalation")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Family Brawler")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Family Familiar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Family Fighter")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Fierce Fliers")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Flock Together")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Flying Brawler")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Humanoid Brawler")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Humanoid Havoc")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\The Lil'Necromancer")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Magic Brawler")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Magical Mayhem")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Master of Magic")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Mechanical Brawler")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Mechanical Melee")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Mousing Around")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Murlocs, Harpies, and Wolvar, Oh My!")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Ragnaros, Watch and Learn")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Roboteer")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\General\\Taming the Wild")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\General\\Taming the Great Outdoors")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\General\\Taming the World")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Undead Brawler")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Unstoppable Undead")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Collect\\Legion\\Raiding with Leashes V: Cuteaclysm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Legion\\Pet Battle Challenge: Deadmines")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Legion\\Pet Battle Challenge: Wailing Caverns")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Collect\\Legion\\Broken Isles Safari")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Crest of Heroism")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Crest of Carnage")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Crest of Devastation")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Top Honors")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\First Step into a Larger World")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Here We Go Again")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Third Time's the Charm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\For Prestige")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Alive for Five")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\The River Six")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Slayin' to Seven")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Don't Hate. Grind to Eight")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Hell. It's About Nine")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Decade of Dominance")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\These Go To Elevan")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Demonic Dozen")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Floor Thirteen")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Fourteen For The Team")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\When You're Fifteen")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\You Are Sixteen")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Going On Seventeen")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Eighteen and Over")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Hell. It's About Nineteen")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Double Decade of Dominance")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Twenty-One Arms Salute")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Catching Twenty-Two")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Protocol 2.3")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Demonic Double Dozen")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Prestige Quartermaster")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Legion\\Demonic Elite")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Legion\\Demonic Combatant")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Seething Shore\\A Good Start")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Seething Shore\\Blood and Sand")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Seething Shore\\Claim Jumper")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Seething Shore\\Death from Above")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Seething Shore\\Master of Seething Shore")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Seething Shore\\Seething Shore Domination")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Seething Shore\\Seething Shore Perfection")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Seething Shore\\Seething Shore Veteran")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Seething Shore\\Seething Shore Victory")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Archaeology\\A Keen Eye")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Archaeology\\The Dwarven Dream")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Archaeology\\Getting Your Hands Dirty")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Archaeology\\Handle With Care")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Archaeology\\Legion Archaeologist")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Archaeology\\Legion Curator")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Archaeology\\No Stone Unturned")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Archaeology\\This Side Up")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Archaeology\\Sifting Through the Sand")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Archaeology\\Surveying the Land")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Cooking\\Everything Tastes Better")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Cooking\\Legion Cooking")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Cooking\\The Legion Menu")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Fishing\\A Cast Above the Rest")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Fishing\\Bigger Fish to Fry")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Fishing\\Fisherfriend of the Isles")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Fishing\\Fishing 'Round the Isles")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Fishing\\Legion Aquaculture")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Fishing\\Legion Fisherman")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Fishing\\The Wish Remover")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Hot Swapper")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Professions\\The Shortest Distance")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\50 World Quests Completed")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\200 World Quests Completed")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\500 World Quests Completed")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\1000 World Quests Completed")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\2500 World Quests Completed")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\5000 World Quests Completed")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\10,000 World Quests Completed")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\A Magic Contribution")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\A Magnificent Contribution")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Ain't No Mountain High Enough")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Assume Command")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Azsuna Matata")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Breaching the Tomb")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Champions of Legionfall")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Crate Expectations")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Defender of the Broken Isles")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Disrupting the Nether")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Good Suramaritan")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Harbinger")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Hatchling of the Talon")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Insurrection")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\It'll Nether Happen")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Level 110")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Leyline Bling")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Lock, Stock and Two Smoking Goblins")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Locked and Loaded")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Loremaster of Legion")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Nightfallen But Not Forgotten")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\No Shellfish Endeavor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Now You're Thinking With Portals")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Pillars of Creation")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Post Haste")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Priority Mail")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Take Command")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Tehd & Marius' Excellent Adventure")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\That's Val'sharah Folks!")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\They See Me Rolling")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\The Total Package")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Variety is the Spice of Life")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Vrykul Story, Bro")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\What a Ripoff!")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Why Can't I Hold All This Mana?")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\You Are Now Prepared!")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Zoom!")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Reputations\\Legion\\Armies of Legionfall")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Reputations\\Legion\\Broken Isles Diplomat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Reputations\\Legion\\Friends in a Broken Land")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Reputations\\Legion\\The Nightfallen")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Reputations\\Legion\\Officer of the Light")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Reputations\\Legion\\Paragon of the Broken Isles")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Reputations\\Legion\\Protector of the Argussian Reach")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Reputations\\Legion\\The Reputable")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\World Events\\Legion Brawler's Guild\\Educated Guesser")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\World Events\\Legion Brawler's Guild\\I Am Thrall's Complete Lack Of Surprise")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\World Events\\Legion Brawler's Guild\\King of the Guild")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\World Events\\Legion Brawler's Guild\\Rumble Club")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\World Events\\Legion Brawler's Guild\\You Are Not The Contents Of Your Wallet")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\World Events\\Darkmoon Faire\\Hey, You're a Rockstar!")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\World Events\\Darkmoon Faire\\Mosh Pit")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\World Events\\Darkmoon Faire\\Perfect Performance")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\World Events\\Darkmoon Faire\\Taking this Show on the Road")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\A Heroic Campaign")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\An Epic Campaign")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\Champions of Power")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\Champions Rise")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\Fighting with Style: Classic")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\Forged for Battle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\Improving on History")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\Lead a Legion")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\Legendary Research")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\Many Many Missions, Handle It!")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\Many Missions")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\Need Backup")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\Quite a Few Missions")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\Raise an Army")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\Roster of Champions")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\So Many Missions")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\There's a Boss In There")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\Training the Troops")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\A Steamy Romance Saga")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Boom Bloom")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Broken Isles Keymaster")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Burn After Reading")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Darker Side")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Dine and Bash")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Heroic: Assault on Violet Hold")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Heroic: Black Rook Hold")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Heroic: Darkheart Thicket")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Heroic: Eye of Azshara")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Heroic: Halls of Valor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Heroic: Neltharion's Lair")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Heroic: Maw of Souls")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Heroic: Return to Karazhan")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Heroic: Seat of the Triumvirate")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Heroic: Vault of the Wardens")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Keystone Challenger")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Keystone Conqueror")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Keystone Initiate")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Keystone Master")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Let it All Out")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Master of Shadows")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Mythic: Assault on Violet Hold")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Mythic: Black Rook Hold")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Mythic: Cathedral of Eternal Night")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Mythic: Darkheart Thicket")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Mythic: Eye of Azshara")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Mythic: Halls of Valor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Mythic: Maw of Souls")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Mythic: Neltharion's Lair")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Mythic: Return to Karazhan")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Mythic: Seat of the Triumvirate")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Mythic: Vault of the Wardens")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\One Night in Karazhan")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\The Rat Pack")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Scared Straight")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Season Tickets")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Welcome the Void")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Arcing Aqueducts")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Betrayer's Rise")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Boneafide Tri Tip")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Chamber of the Avatar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Darkbough")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Deceiver's Fall")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\The Gates of Hell")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Heroic: Trial of Valor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Cenarius")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Chronomatic Anomaly")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Demonic Inquisition")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Desolate Host")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Dragons of Nightmare")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Elerethe Renferal")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Fallen Avatar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Goroth")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Grand Magistrix Elisande")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Guarm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Harjatan")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Helya")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: High Botanist Tel'arn")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Il'gynoth")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Kil'Jaeden")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Krosus")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Maiden of Vigilance")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Mistress Sassz'ine")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Nythendra")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Odyn")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Sisters of the Moon")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Skorpyron")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Spellblade Aluriel")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Star Augur Etraeus")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Tichondrius")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Trilliax")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Ursoc")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Forbidden Descent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Hope's End")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Light's Breach")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Aggramar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Antoran High Command")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: The Coven of Shivarra")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Eonar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Garothi Worldbreaker")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Hounds of Sargeras")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Imonar the Soulhunter")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Kin'garoth")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Portal Keeper Hasabel")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Varimathras")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Nightspire")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Patient Zero")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Rift of Aln")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Royal Athenaeum")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Terrors of the Shore")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Tormented Guardians")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Trial of Valor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Wailing Halls")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\You Ruined Everything!")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Legion Dungeon Hero")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Adventurer of Azsuna")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Adventurer of Highmountain")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Adventurer of Stormheim")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Adventurer of Suramar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Adventurer of Val'sharah")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Bringing Home the Beacon")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Infused and Abused")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Going Up")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Naxt Victim")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Treasures of Azsuna")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Treasures of Highmountain")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Treasures of Stormheim")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Treasures of Suramar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Treasures of Val'sharah")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Feats of Strength\\Raids\\Legion\\Ahead of the Curve: Argus the Unmaker")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Feats of Strength\\Raids\\Legion\\Cutting Edge: Argus the Unmaker")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Feats of Strength\\Raids\\Cutting Edge: Gul'dan")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\General\\Legion\\Brokenly Epic")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Legacy\\Expansion Features\\Artifact or Artifiction")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Legacy\\Expansion Features\\Crucible's Promise")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Legacy\\Expansion Features\\Now You're Cooking with Netherlight")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Legacy\\Expansion Features\\Part of History")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Legacy\\Expansion Features\\Power Ascended")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Legacy\\Expansion Features\\Power Realized")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Legacy\\Expansion Features\\Power Unbound")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Legacy\\Expansion Features\\Power Unleashed")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Legacy\\Professions\\Is There a Medic in the Zone?")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Legacy\\Chapter I: Call of the Archmage")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Legacy\\Chapter II: Gul'dan Strikes Back")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Legacy\\Chapter III: The Foundry Falls")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Legacy\\Chapter IV: Darkness Incarnate")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Anomalous Animals of Argus")
