local ZygorGuidesViewer=ZygorGuidesViewer
if not ZygorGuidesViewer then return end
if UnitFactionGroup("player")~="Horde" then return end
if ZGV:DoMutex("GarrisonHWOD") then return end
ZygorGuidesViewer.GuideMenuTier = "TRI"
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Garrison Buildings\\Small Buildings\\Alchemy Lab")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Garrison Buildings\\Small Buildings\\Enchanter's Study")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Garrison Buildings\\Small Buildings\\Engineering Works")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Garrison Buildings\\Small Buildings\\The Forge")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Garrison Buildings\\Small Buildings\\Gem Boutique")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Garrison Buildings\\Small Buildings\\Salvage Yard")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Garrison Buildings\\Small Buildings\\Scribe's Quarters")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Garrison Buildings\\Small Buildings\\Storehouse")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Garrison Buildings\\Small Buildings\\Tailoring Emporium")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Garrison Buildings\\Small Buildings\\The Tannery")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Garrison Buildings\\Medium Buildings\\Barn")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Garrison Buildings\\Medium Buildings\\Frostwall Tavern")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Garrison Buildings\\Medium Buildings\\Gladiator's Sanctum")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Garrison Buildings\\Medium Buildings\\Lumber Mill")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Garrison Buildings\\Medium Buildings\\Trading Post")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Garrison Buildings\\Large Buildings\\Barracks")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Garrison Buildings\\Large Buildings\\Goblin Workshop")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Garrison Buildings\\Large Buildings\\Spirit Lodge")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Garrison Buildings\\Large Buildings\\Stables")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Garrison Buildings\\Large Buildings\\War Mill")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Garrison Buildings\\Default Buildings\\Fishing Shack")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Garrison Buildings\\Default Buildings\\Frostwall Mines")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Garrison Buildings\\Default Buildings\\Herb Garden")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Garrison Buildings\\Default Buildings\\Menagerie")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Garrison Buildings\\Default Buildings\\Frostwall Shipyard")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Garrison Campaign Guide")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Tanaan Jungle (6.2) Garrison Campaign\\Onslaught at Auchindoun")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Tanaan Jungle (6.2) Garrison Campaign\\The Bane of the Bleeding Hollow")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Tanaan Jungle (6.2) Garrison Campaign\\In the Shadows")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Tanaan Jungle (6.2) Garrison Campaign\\The Warlock")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Garrison Leveling Guide")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Garrison Quests Guide")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Starter Guide")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower 'Doc' Schweitzer")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Abu'gar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Aeda Brightdawn")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Ahm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Aila Dourblade")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Aknor Steelbringer")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Alexi Barov")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Arienne Black")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Auriel Brightsong")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Awarri Blazecall")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Benjamin Gibb")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Bim'ini")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Blook")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Bruto")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Cacklebone")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Cadi Grasshoof")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Candice Morey")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Cheri")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Choluna")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Clever Ashyo")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Coggeye Aimbot")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Croman")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Cyril Fogus")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Dagg")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Dark Ranger Velonara")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Dawn Mercurus")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Dawnseeker Rukaryx")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Deneezo Hailstrike")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Eula Clay")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Faala")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Fazerra")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Fen Tao")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Fo Sho Knucklebump")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Glaiveweaver Xuan")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Goldmane the Skinner")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Gravewalker Gie")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Greatmother Geyah")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Gronnstalker Rokash")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Hannya")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Haomi")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Image of Archmage Vargoth")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Iye")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Ja'kala")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Ka'la")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Kaiel")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Kal'gor the Honorable")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Kaluaka")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Kana'tin")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Karg Bloodfury")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Karga Quickshot")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Karn Steelhoof")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Kaz the Shrieker")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Kil'weh")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Kimzee Pinchwhistle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Lantresor of the Blade")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Leeroy Jenkins")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Leorajh")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Lin Tenderpaw")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Lokra")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Lonan")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Lucy Keller")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Magister Krelas")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Maska")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Matoclaw")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Mau'iti")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Meatball")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Millhouse Manastorm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Morketh Bladehowl")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Motina")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Muaha Stonehide")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Mulverick")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Nat Pagle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Nuan Skydream")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Olin Umberhide")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Penny Clobberbottom")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Phaedra Heartbinder")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Phylarch the Evergreen")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Pikake")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Pleasure-Bot 8000")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Professor Felblast")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Rizei Stormhoof")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Robin Fredericksen")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Ruthia the Unchaste")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Sahale")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Seleria Dawncaller")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Shadow Hunter Rala")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Skalliz Skullslice")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Soulare of Andorhal")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Soulbinder Tuulani")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Spirit of Bony Xuk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Su-Lai Snowpetal")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Taela Shatterborne")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Tak'moa")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Talon Guard Kurekk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Talonpriest Ishaal")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Tama Skyhoof")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Toega")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Tormmok")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Torwa Rimeheart")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Ulna Thresher")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Unkala Stormgrinder")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Utona Wolfeye")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Vella A'nar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Vivianne")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Vol'motu")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Walsh Atkins")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Weaponsmith Na'Shra")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Xen Barleystrike")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Yu'un Tigersbite")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Zen'taki")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Zen'tenbi")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Zen'tiki")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Followers\\Follower Ziri'ak")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Garrison Scouting Missives")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Garrison Jukebox")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-60)\\Garrisons\\Mystery Notebook Questline")
