local ZygorGuidesViewer=ZygorGuidesViewer
if not ZygorGuidesViewer then return end
if UnitFactionGroup("player")~="Alliance" then return end
if ZGV:DoMutex("LevelingALEGION") then return end
ZygorGuidesViewer.GuideMenuTier = "TRI"
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Death Knight\\Death Knight Intro & Artifacts")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Death Knight\\Death Knight Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Death Knight\\Death Knight 7.2 Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Demon Hunter\\Demon Hunter Intro & Artifacts")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Demon Hunter\\Demon Hunter Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Demon Hunter\\Demon Hunter 7.2 Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Druid\\Druid Intro & Artifacts")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Druid\\Druid Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Druid\\Druid 7.2 Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Evoker\\Evoker Intro")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Hunter\\Hunter Intro & Artifacts")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Hunter\\Hunter Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Hunter\\Hunter 7.2 Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Mage\\Mage Intro & Artifacts")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Mage\\Mage Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Mage\\Mage 7.2 Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Monk\\Monk Intro & Artifacts")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Monk\\Monk Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Monk\\Monk 7.2 Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Paladin\\Paladin Intro & Artifacts")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Paladin\\Paladin Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Paladin\\Paladin 7.2 Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Priest\\Priest Intro & Artifacts")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Priest\\Priest Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Priest\\Priest 7.2 Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Rogue\\Rogue Intro & Artifacts")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Rogue\\Rogue Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Rogue\\Rogue 7.2 Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Shaman\\Shaman Intro & Artifacts")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Shaman\\Shaman Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Shaman\\Shaman 7.2 Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Warlock\\Warlock Intro & Artifacts")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Warlock\\Warlock Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Warlock\\Warlock 7.2 Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Warrior\\Warrior Intro & Artifacts")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Warrior\\Warrior Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Warrior\\Warrior 7.2 Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Azsuna")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Highmountain")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Stormheim")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Suramar (45-60)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Val'sharah")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Broken Shore Campaign")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Argus Campaign")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Argus Vindicaar Mission Table Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Balance of Power Questline")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Legion Invasions")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Broken Shore\\Excavator Karla Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Broken Shore\\Anduin Wrynn Questline")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Dalaran Postmaster Quest Line")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Rogue Pickpocketing Quest Line")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\Meatball Order Hall Champion")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-60)\\The Hunt For Illidan Stormrage")
